# Generated by Django 2.2.6 on 2023-04-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pws', '0078_auto_20230405_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexception',
            name='put_to_customer_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='put_to_customer_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderexception',
            name='send_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='send_back_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderexception',
            name='send_back_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderexception',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
